behaviors:
  PlatformJumper:
    trainer_type: ppo
    
    hyperparameters:
      # Params shared between PPO and SAC
      batch_size: 128
      buffer_size: 2048
      learning_rate: 0.0003
      learning_rate_schedule: linear
      
      # PPO specific params
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      
    # Configuration of the neural network (common to PPO/SAC)
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 2
      vis_encode_type: simple
      
    # Environment rewards
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      gail:
        strength: 0.01
        gamma: 0.99
        demo_path: Demonstrations/PlatformJumper_3-7-platform_10m/
        
    # Trainer configurations common to all trainers
    keep_checkpoints: 5
    max_steps: 1000000
    time_horizon: 128
    summary_freq: 30000